export const FALLBACK_LEGAL_STRUCTURES = [
  {
    code: 'LST001',
    title: 'ชื่อประกาศ',
    value: 'LST001',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'indigo',
    export_key: 'TITLE',
    sort_order: 1,
  },
  {
    code: 'LST002',
    title: 'คำปรารภ',
    value: 'LST002',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'success',
    export_key: 'PREAMBLE',
    sort_order: 2,
  },
  {
    code: 'LST003',
    title: 'บทอาศัยอำนาจ',
    value: 'LST003',
    family_codes: ['LFM01', 'LFM02', 'LFM03'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'deep-purple',
    export_key: 'AUTHORITY',
    sort_order: 3,
  },
  {
    code: 'LST004',
    title: 'ข้อ',
    value: 'LST004',
    family_codes: ['LFM01', 'LFM02', 'LFM03'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: true,
    is_required: false,
    color: 'orange',
    export_key: 'CLAUSE',
    sort_order: 4,
  },
  {
    code: 'LST005',
    title: 'วันบังคับใช้',
    value: 'LST005',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'teal',
    export_key: 'EFFECTIVE_DATE',
    sort_order: 5,
  },
  {
    code: 'LST006',
    title: 'บทยกเลิก',
    value: 'LST006',
    family_codes: ['LFM01', 'LFM02'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'red',
    export_key: 'REPEAL',
    sort_order: 6,
  },
  {
    code: 'LST007',
    title: 'บทนิยาม',
    value: 'LST007',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'amber-darken-2',
    export_key: 'DEFINITION_SECTION',
    sort_order: 7,
  },
  {
    code: 'LST008',
    title: 'คำนิยาม',
    value: 'LST008',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: false,
    counts_as_section: false,
    is_required: false,
    color: 'amber',
    export_key: 'DEFINITION',
    sort_order: 8,
  },
  {
    code: 'LST009',
    title: 'บทรักษาการ',
    value: 'LST009',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'brown',
    export_key: 'CUSTODIAN',
    sort_order: 9,
  },
  {
    code: 'LST010',
    title: 'บทเฉพาะกาล',
    value: 'LST010',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'cyan',
    export_key: 'TRANSITIONAL_PROVISION',
    sort_order: 10,
  },
  {
    code: 'LST011',
    title: 'มาตรา',
    value: 'LST011',
    family_codes: ['LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: true,
    is_required: false,
    color: 'blue-grey',
    export_key: 'SECTION',
    sort_order: 11,
  },
  {
    code: 'LST012',
    title: 'หมวด/ส่วน',
    value: 'LST012',
    family_codes: ['LFM01', 'LFM02', 'LFM03', 'LFM04'],
    file_types: ['word', 'pdf'],
    is_head: true,
    counts_as_section: false,
    is_required: false,
    color: 'blue',
    export_key: 'CHAPTER',
    sort_order: 12,
  },
] as const;

export type LegalStructureFileType = 'word' | 'pdf';
export type LegalStructureCode = typeof FALLBACK_LEGAL_STRUCTURES[number]['code'];
export type LegacyChunkType = typeof FALLBACK_LEGAL_STRUCTURES[number]['export_key'] | 'ARTICLE' | 'PARAGRAPH' | 'ITEM' | 'BOOK' | 'PART';
export type ChunkType = LegalStructureCode;

export const LEGACY_CHUNK_TYPE_MAP: Record<string, LegalStructureCode> = {
  TITLE: 'LST001',
  PREAMBLE: 'LST002',
  AUTHORITY: 'LST003',
  CLAUSE: 'LST004',
  ARTICLE: 'LST004',
  PARAGRAPH: 'LST004',
  ITEM: 'LST004',
  EFFECTIVE_DATE: 'LST005',
  REPEAL: 'LST006',
  DEFINITION_SECTION: 'LST007',
  DEFINITION: 'LST008',
  CUSTODIAN: 'LST009',
  TRANSITIONAL_PROVISION: 'LST010',
  SECTION: 'LST011',
  CHAPTER: 'LST012',
  BOOK: 'LST012',
  PART: 'LST012',
};

export function normalizeChunkType(value: string | null | undefined): LegalStructureCode | undefined {
  if (!value) return undefined;
  const normalized = value.trim().toUpperCase();
  if (/^LST\d{3}$/u.test(normalized)) return normalized as LegalStructureCode;
  return LEGACY_CHUNK_TYPE_MAP[normalized];
}
